image: docker:latest

variables:
  MAVEN_CLI_OPTS: "-B --quiet"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_DRIVER: overlay

stages:
  - build
  - package
  - deploy
  - clean

maven-build:
  image: maven:3-jdk-8
  stage: build
  services:
    - docker:dind
  script:
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    paths:
      - target/*.jar
  cache:
    paths:
      - .m2/repository/

docker-build:
  stage: package
  services:
    - docker:dind
  script:
    - docker build --rm -t "quay.io/gjkrupa/s3web:${CI_COMMIT_SHA}" .
    - docker rmi "quay.io/gjkrupa/s3web:${CI_COMMIT_SHA}"
  only:
    - branches

docker-push:
  stage: package
  services:
    - docker:dind
  script:
    - docker login -u "${QUAY_USER}" -p "${QUAY_TOKEN}" quay.io
    - docker build -t "quay.io/gjkrupa/s3web:${CI_COMMIT_TAG}" .
    - docker push "quay.io/gjkrupa/s3web:${CI_COMMIT_TAG}"
    - docker tag "quay.io/gjkrupa/s3web:${CI_COMMIT_TAG}" "quay.io/gjkrupa/s3web:latest"
    - docker push "quay.io/gjkrupa/s3web:latest"
  only:
    - tags
